name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Clear NX cache
        run: npx nx reset
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
      - name: Install npm 10.8.1
        run: |
          npm install -g npm@10.8.1
          npm --version
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH
      - name: Verify npm version
        run: |
          npm --version
          if [[ $(npm --version) != "10.8.1" ]]; then
            echo "npm version is not 10.8.1"
            exit 1
          fi
      - name: Install dependencies
        run: npm ci
      - name: Unset extraheader
        run: git config --global --unset-all http.https://github.com/.extraheader || true
      - name: Set CI to false to prevent treating warnings as errors
        run: echo "CI=false" >> $GITHUB_ENV
      - name: Build
        run: npm run build
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_SAND_07EE82C10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist/portfolio-upwurok"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_SAND_07EE82C10 }}
          action: "close"